### ISSUE TITLE
TypeError undefined is not an object (evaluating '_ref 3.label')

### ISSUE THREAD

**Issue by itsaladin** [hossein-zare/react-native-dropdown-picker#172] opened 2021-01-04 05:08 UTC
**Describe the bug**

**To Reproduce**

Create an expo snack:
[https://snack.expo.io/](https://snack.expo.io/)

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - OS: [iOS, Android]
 - Package version [e.g. 22]

**Additional context**

**Comment by areeb-hub** [comment] 2021-01-05 11:16
This is an issue, please note.

**Comment by hossein-zare** [comment] 2021-01-05 22:03
duplicate of https://github.com/hossein-zare/react-native-dropdown-picker/issues/93

**Closed as completed** 2021-01-16 07:03 UTC
