### ISSUE TITLE
Items are not clickable over a MapView (Android)

### ISSUE THREAD

**Issue by sibandrew** [hossein-zare/react-native-dropdown-picker#351] opened 2021-06-06 18:25 UTC
I am using the expo-managed workflow, and I would need to use the dropdown at the top part of a screen view, and below I have a MapView ([react-native-maps](https://github.com/react-native-maps/react-native-maps)).

After opening the dropdown, items over the MapView are not clickable.

https://user-images.githubusercontent.com/48277672/120935627-043f8380-c704-11eb-9d7f-a020753d335d.mp4

I tried to write a simple code snippet in order to make it easily replicable:

```
import React, { useState } from "react";
import { StyleSheet, View } from "react-native";
import DropDownPicker from "react-native-dropdown-picker";
import MapView from "react-native-maps";

export default function App() {
    const [open, setOpen] = useState(false);
    const [value, setValue] = useState(null);
    const [items, setItems] = useState([
        { label: "Apple", value: "apple" },
        { label: "Banana", value: "banana" },
    ]);

    return (
        <View style={styles.container}>
            <View style={styles.top}>
                <DropDownPicker
                    open={open}
                    value={value}
                    items={items}
                    setOpen={setOpen}
                    setValue={setValue}
                    setItems={setItems}
                    zIndex={1000}
                />
            </View>

            <MapView style={styles.map}></MapView>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: "column",
        backgroundColor: "yellow",
    },
    top: {
        flexDirection: "column",
        marginTop: 40,
        height: 70,
        zIndex: 10,
    },
    map: {
        flex: 1,
        zIndex: 0,
    },
});
```

The same code is working perfectly on iOS.

I would appreciate it if you have some suggestions, thank you in advance!

**Comment by hossein-zare** [comment] 2021-06-06 18:46
Hello,

Remove `zIndex: 10` from the `top` style, instead do:
```jsx
<View style={[styles.top, Platform.OS !== 'android' && {
  zIndex: 1000
}]}>
  ...
</View>
```
_Don't forget to `import { Platform } from 'react-native'`_

**Comment by mohammadrahmanian** [comment] 2021-06-09 06:43
I'm using this dropdown picker inside a modal and I have the exact same issue. I've removed the zIndex for android devices but I still can't select any items from the dropdown list. this is the code from my custom styles related to the zIndex:
`...(Platform.OS !== 'android' && {
   zIndex: 11
}),`

**Comment by hossein-zare** [comment] 2021-06-09 10:35
Hello @mohammadrahmanian ,
Make sure you've followed [the rules](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules).

By the way, Your description of the issue is not enough.

**Comment by Aexonic-Abhishek** [comment] 2021-08-04 12:57
I'm also getting same issue. Not able to click dropdown items on android. It's working on iOS though.
  <DropDownPicker
        placeholder={props.placeholder}
        placeholderStyle={[styles.placeholderStyle, props.placeholderStyle]}
        style={[styles.dropdownStyle, props.style]}
        textStyle={[styles.textStyle, props.textStyle]}
        dropDownContainerStyle={[styles.dropDownContainerStyle]}
        selectedItemContainerStyle={styles.selectedItemContainerStyle}
        selectedItemLabelStyle={styles.selectedItemLabelStyle}
        open={props.open}
        value={props.value}
        items={props.data}
        setOpen={props.setOpen ? (value) => props.setOpen(value) : null}
        setValue={props.setValue ? (value) => props.setValue(value) : null}
        showTickIcon={false}
        onChangeValue={props.onChangeValue ? (value) => props.onChangeValue(value) : null}
        maxHeight={props.maxHeight}
        loading={props.loading}
        activityIndicatorSize={15}
        activityIndicatorColor={'#000'}
    />

**Comment by boerkey** [comment] 2021-09-03 18:28
> Hello @mohammadrahmanian ,
> Make sure you've followed [the rules](https://hossein-zare.github.io/react-native-dropdown-picker-website/docs/rules).
> 
> By the way, Your description of the issue is not enough.

I checked it and tried as suggested but not working.. This is very big gotcha for this package..

**Comment by mikehardy** [comment] 2021-09-03 18:30
Have you tried dynamically setting zIndex on *all* view hierarchies in your component tree based on dropdown state? That is, when dropdown is open dynamically setting all zIndex to 0 except the dropdown, and setting dropdown to 1? That is a strategy I used to get past a slightly different zIndex issue.

Dynamically sized / overlapping components on the web and in native are simply difficult. It's not so much a "gotcha" as a "this is how it works, and it's hard to get right" in my experience here so far

**Comment by boerkey** [comment] 2021-09-03 18:37
I dont know still, I mean we use this packages to makes things easier while building UI and just to be able to use this package, we need edit all zIndexes of screen.. Feels really weird

**Comment by mikehardy** [comment] 2021-09-03 18:47
Have you read the CSS rules for zIndex and how component hierarchies work? They simply are weird. But for view hierarchies, they are the rules, you just have to submit. Examine https://philipwalton.com/articles/what-no-one-told-you-about-z-index/ + https://github.com/facebook/react-native/issues/8970

**Comment by boerkey** [comment] 2021-09-03 19:52
I didnt mean for rules or depths of it, I simply said it for how easy to use the functionality.  

For example I just switched to some other package which is updated 2 years ago and in this case it works clear and better. Like I dont need to edit all my views with zIndexes etc just to make this work.

https://github.com/sohobloo/react-native-modal-dropdown

@mikehardy Looks like you always want nice and sweet comments from devs who use packages to ease things? 😄

**Comment by boerkey** [comment] 2021-09-03 20:00
@sibandrew you can check this package as well, at least it solved my issues which is similar to yours. I tried few but this one looks easiest to use for now.

https://github.com/sohobloo/react-native-modal-dropdown

**Comment by mikehardy** [comment] 2021-09-03 20:32
Thanks for the links to other packages

> @mikehardy Looks like you always want nice and sweet comments from devs who use packages to ease things? smile

Don't ever get personal, you don't know me.

**Comment by boerkey** [comment] 2021-09-03 20:37
@mikehardy 

Haha I think I learned some of your attitudes already(since firebase bug discussion) 😄 I dont mean to be negative, just take my comments as some suggestions to be improved thats it.

**Comment by mikehardy** [comment] 2021-09-03 20:40
My attitude is focus on the code, show the reproduction, find the cause, make reproducible, referenceable things. Opinions are easy

**Comment by boerkey** [comment] 2021-09-03 20:42
@mikehardy it means you are closed the opinions then? :) Also you get the idea right, that opinions occur after some experience with the related thing. We just dont write these opinions and experiences randomly, right?

**Comment by mikehardy** [comment] 2021-09-03 20:45
Do you have a https://duckduckgo.com/?t=canonical&q=minimum+reproducible+example you'd like to share? Perhaps there is a documentation update that would lead people to successful usage patterns. Or perhaps there is a bug.

Opinions are easy, forward progress requires work.

Literally merged two PRs in the 4 minutes since I came back here to make this, my finally meta comment.

PRs happily accepted, as ever

**Comment by boerkey** [comment] 2021-09-03 20:49
Well still question is so easy, why we have to add all the zIndex prop to all views related with this DropDownPicker?

Also the same functionality is very easy to use in other package WHICH is updated 2 years ago. 

But yeah PRs are accepted to make a product better than other one which is not UPDATED last 2 years. Good luck with improving it with zIndex shows. 👍

**Comment by mikehardy** [comment] 2021-09-03 20:52
I would like to know the answer to that question as well. It would be great if you found out why and shared it. It's a common problem here.

**Comment by boerkey** [comment] 2021-09-03 20:53
> I would like to know the answer to that question as well. It would be great if you found out why and shared it. It's a common problem here.

Looks like some answer or kind of solution has discovered 2 YEARS ago, so maybe it can inspire people who work for this package.

**Comment by mikehardy** [comment] 2021-09-03 20:56
Oh I see. Absolute positioning. That's messy [absolute positioning will not allow any flex so layouts become brittle, and screen measurement is difficult in certain contexts].

https://github.com/sohobloo/react-native-modal-dropdown/blob/eee01b148923020b277cefbf11b9fce79a1ed74a/components/ModalDropdown.js#L124

Cheers

**Comment by boerkey** [comment] 2021-09-03 20:58
Messy sounded like 'opinion' and its not a proper thing as you said right :) Think as user of the product, how easy to use some UI library and benefit from it?

Cheers, good luck

**Comment by mikehardy** [comment] 2021-09-03 21:02
fair point. edited: That's messy [absolute positioning will not allow any flex so layouts become brittle, and screen measurement is difficult in certain contexts].

**Closed as completed** 2021-12-13 22:59 UTC
