### ISSUE TITLE
I am unavailable to select an item.

### ISSUE THREAD

**Issue by RNTop** [hossein-zare/react-native-dropdown-picker#88] opened 2020-08-22 05:45 UTC
**Describe the bug**
 When I set backgroundColor or borderColor at parent view of dropdown picker, then I am unavailable to choose any item. so touch event does not working . not sure why it is depends of background color or border color.

**To Reproduce**
```
 <View style={styles(theme).dropdown}>
                                <Text style={styles(theme).country_text}>{Strings.language}</Text>
                                <View style={styles(theme).dropdownWrapper}>
                                    <DropDownPicker
                                        items={languages}
                                        defaultValue={language}
                                        containerStyle={{ height: 40, width: '100%' }}
                                        placeholderStyle={{ color: theme.text }}
                                        selectedLabelStyle={{ color: theme.text }}
                                        arrowColor={'black'}
                                        showArrow
                                        itemStyle={{ justifyContent: 'flex-start', }}
                                        style={{ backgroundColor: theme.itemBg }}
                                        onChangeItem={item => this.setState({
                                            language: item.value
                                        })}
                                    />
                                </View>
                     </View>
  dropdown:{         
        alignSelf:'center',
        paddingHorizontal: Dimensions.px20,
        paddingVertical: Dimensions.px10, 
        margin:Dimensions.px15,  
        // backgroudColor:'red'     
    },
    dropdownWrapper: {
        paddingHorizontal: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        height: Dimensions.px40,
        marginLeft: Dimensions.px20,
        width: '100%'
    },
```

**Screenshots**
![Screenshot_1598074659](https://user-images.githubusercontent.com/51260671/90949733-d4dfb480-e418-11ea-8a2e-d709561aa585.png)

**Info (please complete the following information):**
 - OS :Android
 - Package version 3.1.11

**Comment by hossein-zare** [comment] 2020-08-23 09:26
duplicate of https://github.com/hossein-zare/react-native-dropdown-picker/issues/85

**Closed as completed** 2020-08-26 08:23 UTC
Labels: duplicate
