### ISSUE TITLE
Undefined is not an object (evaluating '_ref.label')

### ISSUE THREAD

**Issue by nolife08021** [hossein-zare/react-native-dropdown-picker#93] opened 2020-08-28 03:44 UTC
This error appear when i try to select an option.
**It works without "defaultValue", but i need it.**
  ```
  const [item, setItem] = useState('item1')


<DropDownPicker
       items={[
           {label: 'Item 1', value: 'item1'},
           {label: 'Item 2', value: 'item2'},
       ]}
       defaultValue={item}
       onChangeItem={item => setItem(item)}
       ...
    />
```

**Comment by hossein-zare** [comment] 2020-08-28 09:19
Hello,

Update the package to the latest version.
Also this is what your component should look like:
```javascript
<DropDownPicker
     items={[
         {label: 'Item 1', value: 'item1'},
         {label: 'Item 2', value: 'item2'},
     ]}
     defaultValue={item}
     onChangeItem={item => setItem(item.value)}
     ...
  />
````

**Comment by DurgeshSupraDigit** [comment] 2020-08-31 10:32
I am also trying to Use the DefaultValue ,
However i m loading the dropDown Items from API .
so when i set a Default Value with these dropDown Items from API , it gives me Choice.Label error 

2.But if I use a HARD CODED array for ITEMS instead of loading them from API . it shows the Default Value.

**Comment by hossein-zare** [comment] 2020-08-31 11:09
@DurgeshSupraDigit 
duplicate of https://github.com/hossein-zare/react-native-dropdown-picker/issues/96#issuecomment-683262397

**Comment by nolife08021** [comment] 2020-09-01 03:09
> Hello,
> 
> Update the package to the latest version.
> Also this is what your component should look like:
> 
> ```js
> <DropDownPicker
>      items={[
>          {label: 'Item 1', value: 'item1'},
>          {label: 'Item 2', value: 'item2'},
>      ]}
>      defaultValue={item}
>      onChangeItem={item => setItem(item.value)}
>      ...
>   />
> ```

Solved. Thank you.

**Closed as completed** 2020-09-01 03:09 UTC

**Comment by ghulamhaider1** [comment] 2021-06-03 12:00
Hello,
Can we use Object as a value and set object as defaultValue. I am getting `Cannot read property 'label' of undefined`

I am using `version ^3.6.3`

**Comment by ghulamhaider1** [comment] 2021-06-03 12:20
> Hello,
> Can we use Object as a value and set object as defaultValue. I am getting `Cannot read property 'label' of undefined`
> 
> I am using `version ^3.6.3`

I managed to resolve this issue by JSON.stringify() the value. 

Thank you for this package. it's awesome 👍

**Comment by noumannaveed** [comment] 2022-01-11 11:56
defaultValue={item.label,item.value}
