### ISSUE TITLE
when Out of focus the dropdown does not auto close

### ISSUE THREAD

**Issue by harry238** [hossein-zare/react-native-dropdown-picker#155] opened 2020-11-23 18:33 UTC
When we open the dropdown and later click outside the drop down it does not auto close, we have to close it manually,
I cannot find any solution for the same. if there's any kindly let me know

**Comment by hossein-zare** [comment] 2020-11-24 07:23
duplicate of https://github.com/hossein-zare/react-native-dropdown-picker/issues/119

**Closed as completed by hossein-zare** 2020-11-24 07:23 UTC
